url: https://csiu.github.io
baseurl:
headerimg:
#img/header-bg.png

# Site settings
title: Celia Siu
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# # Team names, titles and social links
# people:
# - name: #
#   pic: #
#   position: #
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/celiassiu
  - title: github
    url: http://github.com/csiu
  - title: stack-overflow
    url: http://stackoverflow.com/users/2364901/csiu
  - title: medium
    url: https://medium.com/@celiassiu
  - title: linkedin
    url: https://www.linkedin.com/in/celiasiu

# Postal address (add as many lines as necessary)
address:
  - line: Vancouver, BC, Canada

# Build settings
markdown: kramdown
permalink: pretty
